name: print ecco hello 
on:
  push:
    branches:
    - main
jobs:
  my_job:
    name: deploy to staging
    runs-on: self-hosted
    steps: 
    - name: eco
      run: | 
        echo "Hello"
        
      
