name: Example with Artifacts

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello"
      - name: get code
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with: 
          node-version: 18  
      - name: install dependencies
        run: npm ci    
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Build the code (example: fake build command)
      - name: Build project
        run: |
          mkdir output
          cd output
          touch build.txt
          echo "This is the build artifact" > build.txt
          echo $build.txt

      # Step 3: Upload the build output as an artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            output/ # The directory or file to upload
            package.json

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build # Ensures this job runs after the 'build' job

#     steps:
#       # Step 1: Download the artifact uploaded by the 'build' job
#       - name: Download artifact
#         uses: actions/download-artifact@v4
#         with:
#           name: build-artifact

#       # Step 2: Deploy (example: fake deploy command)
#       - name: Deploy project
#         run: |
#           ls -l # List the downloaded artifact
