name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context  
        run: echo "${{ toJSON(github) }}"        #data provoded by github
      - name: Output GitHub context  repository owner
        run: echo "${{ toJSON(github.repository_owner) }}"  

       