name: my-first-workflow
on: push
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello"
      - name: get code
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with: 
          node-version: 18  
      - name: install dependencies
        run: npm ci
      - name: fix dependencies
        run: npm audit fix        
      - name: run test
        run: npm test       